language: csharp
solution: DoggoApp.sln
mono: none
dotnet: 2.1.300

install:
  - dotnet restore src/DoggoApp/
  - dotnet build src/DoggoApp/
  
script:
  - dotnet pack src/DoggoApp/ -c Release
  - dotnet pack src/DoggoApp/ -c Release --version-suffix $TRAVIS_JOB_ID
  
deploy:
  - provider: releases
    api_key: $GITHUB_OAUTH_TOKEN
    on:
      tags: true
