language: csharp
solution: DoggoApp.sln
mono: none
dotnet: 2.1.300

install:
  - dotnet restore src/
  
script:
  - dotnet build src/
  - dotnet test src/DoggoApp.Tests/DoggoApp.Tests.csproj
  - dotnet pack src/DoggoApp/ -c Release
  - dotnet pack src/DoggoApp/ -c Release --version-suffix ci-$TRAVIS_BUILD_NUMBER
  
deploy:
  - provider: releases
    api_key: $GITHUB_OAUTH_TOKEN
    on:
      tags: true
  - provider: script
    skip_cleanup: true
    script: dotnet nuget push src/DoggoApp/bin/Release/DoggoApp.*ci-$TRAVIS_BUILD_NUMBER --api-key $MYGET_APIKEY --source https://www.myget.org/F/identisign/api/v2/package 
    on:
      branch: master
