language: csharp
solution: DoggoApp.sln
mono: none
dotnet: 2.1.300

env:
  global:
    - IDFY_MOCK_SERVER_VERSION=0.0.1

before_install:
  # Download, unpack and start the Idfy Mock Server
  - |
    mkdir -p idfy-mock-server/idfy-mock-server_${IDFY_MOCK_SERVER_VERSION}/
    curl -L "https://github.com/idfy-io/idfy-mock-server/releases/download/v${IDFY_MOCK_SERVER_VERSION}/idfy-mock-server_${IDFY_MOCK_SERVER_VERSION}.zip" -o "idfy-mock-server/idfy-mock-server_${IDFY_MOCK_SERVER_VERSION}.zip"
    unzip "idfy-mock-server/idfy-mock-server_${IDFY_MOCK_SERVER_VERSION}.zip" -d "idfy-mock-server/idfy-mock-server_${IDFY_MOCK_SERVER_VERSION}/"
    dotnet "idfy-mock-server/idfy-mock-server_${IDFY_MOCK_SERVER_VERSION}/Idfy.MockServer.dll" &

install:
  - dotnet restore src/
  
script:
  - dotnet build src/
  - dotnet test src/DoggoApp.Tests/DoggoApp.Tests.csproj
  - dotnet pack src/DoggoApp/ -c Release
  - dotnet pack src/DoggoApp/ -c Release --version-suffix ci-$TRAVIS_BUILD_NUMBER
  
deploy:
  - provider: releases
    api_key: $GITHUB_OAUTH_TOKEN
    on:
      tags: true
  - provider: script
    skip_cleanup: true
    script: dotnet nuget push src/DoggoApp/bin/Release/DoggoApp.*ci-$TRAVIS_BUILD_NUMBER --api-key $MYGET_APIKEY --source https://www.myget.org/F/identisign/api/v2/package 
    on:
      branch: master
