version: 1.2.0.{build}
image: Visual Studio 2017

before_build:
  # Display .NET Core version
  - cmd: dotnet --version
  # Display minimal restore text
  - cmd: dotnet restore ./src/DoggoApp/DoggoApp.csproj
