# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

name: 1.0.$(Rev:r)

trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

variables:
  buildConfiguration: 'Release'

steps:
- script: dotnet build src/ --configuration $(buildConfiguration)
  displayName: 'dotnet build $(buildConfiguration)'
- task: NuGetCommand@2
  inputs:
    command: pack
    packagesToPack: 'src/DoggoApp/DoggoApp.csproj'
    versioningScheme: byBuildNumber
- task: NuGetCommand@2
  displayName: 'NuGet push'
  inputs:
    command: push
    publishVstsFeed: 'TestFeed'